### ISSUE TITLE
Prevent changing code that results in infinite loops

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/hour-of-code#19]
Looking at the [code](https://github.com/FreeCodeCamp/hour-of-code/blob/master/challenges.js) I think we could hide the end of the loop to prevent people from being able to change it. 

Alternatively, we could change the copy to say - "if you change this, you risk creating an infinite loop and crashing your browser. Then you would have to start over." 

That way teachers immediately know the solution - to let the browser crash, then restart them. Otherwise, teachers will scratch their heads.

**Comment by Cinders-P** [comment]
Hid the line so they can't edit it. Hopefully nobody randomly types "n--;".
